company:
  name: Colegio Santo Anjo

server:
  timezone: America/Sao_Paulo

ssl:
  email: admin@colegiosantoanjo.tech

proxy:
  network: oces_proxy
  subnet: 172.18.0.0/16
  trusted_ip: 172.18.0.2

instances:

  te:
    domain: te.colegiosantoanjo.tech
    port: 3001

  academico:
    domain: academico.colegiosantoanjo.tech
    port: 3002

  dp:
    domain: dp.colegiosantoanjo.tech
    port: 3003

  adm:
    domain: adm.colegiosantoanjo.tech
    port: 3004

  paulo:
    domain: paulo.colegiosantoanjo.tech
    port: 3005
