services:

  traefik:

    image: traefik:v3.7.6

    container_name: oces-traefik

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    environment:
      DOCKER_API_VERSION: "1.40"

    ports:
      - "80:80"
      - "443:443"

    networks:
      oces_proxy:
        ipv4_address: 172.18.0.2

    command:
      - --configFile=/etc/traefik/traefik.yml

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./letsencrypt:/letsencrypt
      - ./logs:/logs

networks:
  oces_proxy:
    external: true